create table book(
    id INTEGER GENERATED BY DEFAULT as IDENTITY,
    author varchar(30),
title varchar(30),
   year INTEGER,
   primary key (id));

insert into book(author, title, year)
VALUES ('Tolstoy', 'Война и мир', 1867),
       ('Tolstoy', 'Живой труп',1911);