create table book(
    id INTEGER GENERATED BY DEFAULT as IDENTITY,
    title varchar(30),
   year INTEGER,
   primary key (id));

insert into book(author, title, year)
VALUES ('Tolstoy', 'Война и мир', 1867),
       ('Tolstoy', 'Живой труп',1911);

create table author(
    id integer generated by default as identity,
    name varchar(30);
    surname varchar(30);
    patronymic varchar(30);
    primary key(Id));
insert into author(name,patronymic,surname)
values ('L','N','Tolstoy'),
       ('A','S','Pushkin');