create table book(
    id INTEGER GENERATED BY DEFAULT as IDENTITY,
    title varchar(30),
   year INTEGER,
   author_id integer,
   primary key (id));

insert into book(title, year, author_id)
VALUES ('Война и мир', 1867,1),
       ('Живой труп',1911,2),
        ('Лукаморье',1895,2);

create table author(
    id integer generated by default as identity,
    name varchar(30),
    patronymic varchar(30),
    surname varchar(30),
    primary key (id));
insert into author(name,patronymic,surname)
values ('L','N','Tolstoy'),
       ('A','S','Pushkin');